### ISSUE TITLE
Really Large Trees

### ISSUE THREAD

**Issue by daubin427** [Trinovantes/capted#1]
Hello!,

  Thank you so very much for making this!  I found an issue when creating really large trees and doing an edit distance.  I modified the test_runner to take in two files.  The files were pre-processed in to tree bracket format.  When I did a tree edit distance of a few hundred bytes vs 200kiloBytes the test_runner failed.  I troubleshot it down to this line:

`lib/node/NodeIndexer.h`
`line 146`
`preL_to_desc_sum[preorder] = ((currentSize + 1) * (currentSize + 1 + 3)) / 2 - currentDescSizes;`

`((currentSize + 1) * (currentSize + 1 + 3))`
could be above 0x7fff ffff, then the result is negative.  So one quick fix was to
change these variables to be long int:
`int indexNodes(N* node, int postorder) {`
`100         // Initialise variables.`
`101         long int currentSize = 0;`
`102         long int childrenCount = 0;`
`103         long int descSizes = 0;`
`104         long int krSizesSum = 0;`
`105         long int revkrSizesSum = 0;`
`106         long int preorder = preorderTmp;`
`107         long int preorderR = 0;`
`108         long int currentPreorder = -1;`

While my testing with this change was positive, I'm not sure it is the best solution.  Or perhaps not the most complete.  However, I did want to bring it to your attention.

Thank you :)

**Comment by Trinovantes** [comment]
Thanks for bug report! It's definitely not something I expected to happen because my intended use cases were relatively small.

You're right that changing the types to long will fix it. Just to be safe, I've changed all the ints in the library to a typedef that can either be int64 or int32 depending on the presence of a new preprocessor flag `-DCAPTED_LARGE_TREES`.

https://github.com/Trinovantes/capted/blob/master/Makefile#L17

I'll keep the default to int32 for performance sake but you can use int64 for large test cases.
